data_files: [
    '/home/hice1/drauthan3/scratch/BDA_project/prune/train.jsonl',
    '/home/hice1/drauthan3/scratch/BDA_project/prune/test.jsonl'
]

train_processors: {
  sft: {type: 'CaptionProcessor', image_size: 224, min_scale: 0.5, randaug: False}
}

valid_processors: {
  sft: {type: 'DefaultProcessor', image_size: 224}
}